#Vagrant.configure("2") do |config|
#  config.vm.provider :libvirt do |libvirt|
#    libvirt.driver = "kvm"
##    libvirt.host = 'localhost'
##    libvirt.uri = 'qemu:///system'
#  end
##  config.vm.define "new" do |custombox|
##    custombox.vm.box = "custombox"
##    custombox.vm.provider :libvirt do |test|
##      test.memory = 1024
##      test.cpus = 1
##    end
##  end
## end
Vagrant.configure('2') do |config|
        config.vm.provider :libvirt do |libvirt|
                libvirt.driver = 'kvm'
                libvirt.connect_via_ssh = false
                libvirt.username = 'root'
                libvirt.storage_pool_name = 'default'
        end
end
